add config file for dynamic-profiler

diff --git a/power-management/powerpm-suite/dynamic-profiler/dynamic-profiler b/power-management/powerpm-suite/dynamic-profiler/dynamic-profiler
--- a/power-management/powerpm-suite/dynamic-profiler/dynamic-profiler
+++ b/power-management/powerpm-suite/dynamic-profiler/dynamic-profiler
@@ -1,63 +1,27 @@
 #!/bin/bash
-
-## POWER PROFILE COMMANDS ##
-# set these up to match your power profile backend (power-profiles, tuned, etc)
-# they don't have to be all different! For example, you can set all three to powersave if you want.
-
-# The following three are designed to be run when connected to an AC power source.
-AC_PERFORMANCE="tuned-adm profile throughput-performance"
-AC_BALANCED="tuned-adm profile throughput-performance"
-AC_POWER="tuned-adm profile balanced"
-# The following three are designed to be run when on battery.
-BAT_PERFORMANCE="tuned-adm profile balanced"
-BAT_BALANCED="tuned-adm profile powersave"
-BAT_POWER="tuned-adm profile powersave"
-
-## CPU THRESHOLDS ##
-# Once cpu usage is greater than the threshold, turbo boost is activated.
-# Once again, the first value is for AC, the second for battery mode.
-AC_TURBO_CPU_THRESHOLD="45"
-BAT_TURBO_CPU_THRESHOLD="55"
-
-## LOAD DELTA THRESHOLDS ##
-# at what change in load values should the power governer automatically switch to PERFORMANCE
-# load deltas are just difference in load values between 4 seconds. For example, 1.82 - 1.20 = 0.62
-# Once again, the first value is for AC, the second for battery mode.
-AC_LOAD_DELTA_THRESHOLD="0.30"
-BAT_LOAD_DELTA_THRESHOLD="0.35"
-
-## GOVERNOR SWITCHING (CPU USAGE) ##
-# limits at which to switch to a more powerful or weaker power governor
-# generally, you can treat LOWER_CPU_THRESHOLD as the point between POWER and BALANCED
-# HIGHER_CPU_LIMIT is the point between BALANCED and PERFORMANCE
-# For example, if you have a cpu usage greater than LOWER_CPU_THRESHOLD but lower than HIGHER_CPU_THRESHOLD,
-# you will most likely have the BALANCED profile set.
-
-# The following two are designed to be used when connected to an AC power source.
-AC_LOWER_CPU_THRESHOLD="25"
-AC_HIGHER_CPU_THRESHOLD="45"
-# The following two are designed to be run when on battery.
-BAT_LOWER_CPU_THRESHOLD="35"
-BAT_HIGHER_CPU_THRESHOLD="65"
-
-# prints out the load delta and cpu usage as debugs to logs. The format as follows:
-# LOAD DELTA: -4, CPU: 3, NO_TURBO: 1
-# Load deltas are reported in HUNDREDTHS! (15 = 0.15 difference)
-# No_turbo values are 1 (turbo off), and 0 (turbo on)
-# no matter this setting, you will see messages of the switches between power profiles
-# Set DEBUG_LOG to 1 to enable it, any other value to disable it
-DEBUG_LOG=0 #default disabled
-
 ######################################################################
 ## DO NOT MODIFY BELOW THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING ##
 ######################################################################
+USER_CONFIG="$1"
+if [ ! -z "$USER_CONFIG" ]; then
+  echo "User config file passed. Using config file at $USER_CONFIG"
+  if [ -f "$USER_CONFIG" ]; then
+    . "$USER_CONFIG"
+  else
+    echo "Config file not found. Exiting..."
+    exit 1
+  fi
+else
+  echo "Using default config file at /etc/dynamic-profiler.conf"
+  . /etc/dynamic-profiler.conf
+fi
 
 # Script to automatically change power management settings based on system usage.
 rm /tmp/dynamic-profiler
 
 #precheck tmp file
 if ! [ -f /tmp/dynamic-profiler ]; then #create a tmp file
-  echo "No tmp file found. Creating as /tmp/dynamic-profiler"
+  echo "No tmp file found. Creating as /tmp/dynamic-profiler..."
   touch /tmp/dynamic-profiler > /dev/null
 fi
 
@@ -121,9 +85,14 @@ debug_log () {
 
 ## Main loop
 IS_LOCKED=0
+PMTOGGLE=5
 while true
 do
   if [[ $(cat /tmp/pmtoggle) == "1" ]]; then
+      if [[ "$PMTOGGLE" != 1 ]]; then
+        echo "Connected to AC. Switching to AC mode."
+        PMTOGGLE=1
+      fi
       PERFORMANCE="$AC_PERFORMANCE"
       BALANCED="$AC_BALANCED"
       POWER="$AC_POWER"
@@ -132,6 +101,10 @@ do
       LOWER_CPU_THRESHOLD="$AC_LOWER_CPU_THRESHOLD"
       HIGHER_CPU_THRESHOLD="$AC_HIGHER_CPU_THRESHOLD"
   else
+      if [[ "$PMTOGGLE" != "0" ]]; then
+        echo "Disconnected from AC. Switching to battery mode."
+        PMTOGGLE=0
+      fi
       PERFORMANCE="$BAT_PERFORMANCE"
       BALANCED="$BAT_BALANCED"
       POWER="$BAT_POWER"
@@ -145,9 +118,9 @@ do
       echo "Lock file found. Waiting for manual instruction."
       IS_LOCKED=1
     fi
-    echo "" | tee /tmp/dynamic-profiler > /dev/null
+    echo "locked" | tee /tmp/dynamic-profiler > /dev/null
     if [ -f /tmp/dynamic-profiler-turbo-on ]; then
-      echo "0" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo > /dev/null 
+      echo "0" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo > /dev/null
       echo "Turbo Mode enabled manually"
       rm /tmp/dynamic-profiler-turbo-on
     elif [ -f /tmp/dynamic-profiler-turbo-off ]; then
